[package]
name = "ignition"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9"
log = "0.4"

winit = "0.26"
wgpu = "0.12"
pollster = "0.2"

image = "0.23"
cgmath = "0.18"
bytemuck = { version = "1.4", features = [ "derive" ] }


game_loop = { path = "macros/game_loop" }
